name: Deploy Pipeline

on:
  workflow_run:
    workflows: ["Build Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull santoshpagire/git-action-node_app:latest
    - name: Delete Old docker container
      run: sudo docker rm -f node-app-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8080:8080 --name node-app-container santoshpagire/git-action-node-app